### PR TITLE
Removed unused XML files from library project and fix menu bug.

### PR DESCRIPTION
**Pull request by hwrdprkns**
We don't need these XML files anymore because we are not using a tablet boolean to resize our SlidingMenu view due to differing status bar sizes.

### CODE REVIEW

**Comment by hwrdprkns** [comment]
There was a bug in your code with the content view of the sliding window. The content view needs to be offset as well as the menu itself.

**Comment by jfeinstein10** [comment]
Did you fix it?

**Comment by hwrdprkns** [comment]
Yes, I did fix it. Thanks for merging! This library is awesome.

**Comment by jfeinstein10** [comment]
Thanks for fixing it and for contributing so much in such a short amount of time! Since the summer, I haven't been able to put as much into this library as I would like. Classes and problems sets and projects getting in the way haha.

**Comment by hwrdprkns** [comment]
@jfeinstein10 : Hah, I know the feeling. I was in the same boat a few months ago with EE. Let me know if there is any other way I can help/ be of use. 

I've been looking for an Open Source project to contribute to, and I'm quite taken with this one! :-)

**Pull request merged**
