### PR TITLE
StartWithMenuOpen

### PR DESCRIPTION
**Pull request by frankiesardo**
I've added a functionality StartWithMenuOpen. This allows an activity to be created showing the behind view and then animating a toggle all in a line of code. This functionality is especially useful for those trying to emulate Prixing style of SlidingMenu. 

This functionality is better illustrated with the example introduced in the Example project. A tap in the behind view start a new activity overriding the pending transitions. This will create an effect of refreshing   the above view while the menu is still open. After a certain amount of millis the menu is then closed, all without giving the user the sensation of a new activity showing on top of the previous one, but leaving the back stack untouched.

The only thing that the user should do to implement this pattern effectively is to:
1) override the pending transition between the activities that start with the menu open
2) display the behind view in the new activity in the same way as the behind view of the previous activity. This normally require passing the scrolling index to the new activity, that will scroll the behind view accordingly.

Hope you find this useful.

### CODE REVIEW

**Comment by jfeinstein10** [comment]
Awesome contribution! Thanks a lot :)
I'll review it as soon as I have some time.

**Comment by frankiesardo** [comment]
Happy to hear that. When you have time check at my repo for an update example that better illustrates how the pattern works.

**Comment by kieran-fleming** [comment]
I like everything except breaking my code with the change to getSlidingMenu().toggle() :-)

**Comment by jfeinstein10** [comment]
For now, the solution to this is to call showContent in onPostCreate

**Pull request closed without merging**
