### PR TITLE
Fix for #181.

### LINKED ISSUE #181: TOUCHMODE_MARGIN  not working on unclickable layouts
Hi,

I just noticed that `TOUCHMODE_MARGIN`  doesn't work for some of my layouts.
e.g. if you try to set content  with an empty `LinearLayout` it won't work, but if you put a `Button` in the layout:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent" 
    android:background="@android:color/background_dark"
    >
    <Button 
        android:layout_width="match_parent"
        android:layout_height="200dp"/>
</RelativeLayout>
```

it will work, but only on clickable element - the button

I came to conclusion that view must be clickable, and indeed it's enough to set `android:clickable="true"` to make  `TOUCHMODE_MARGIN`  work

### PR DESCRIPTION
**Pull request by hwrdprkns**
If sliding is enabled, but the view isn't clickable then the menu can't be opened because touch events will not be registered.

This commit assumes that if you want sliding enabled, you want your above view to be clickable as well (a good assumption). Also, adding the standard Android build.xml file so that builds can be done using ant.

Fixes #181

### CODE REVIEW

**Comment by jfeinstein10** [comment]
What would be the downside of just setting it to clickable always?

**Comment by hwrdprkns** [comment]
If sliding isn't enabled and the view isn't meant to be clickable then it's kind of unnecessary to set it to be clickable, right?

**Comment by jfeinstein10** [comment]
I think this was fixed this morning. Can you check on whatever test case you were using?

**Comment by hwrdprkns** [comment]
@jfeinstein10 :+1: Thing seem to work as intended now. Thanks for the fix!

**Comment by jfeinstein10** [comment]
Wonderful news :smile:

**Pull request closed without merging**
