### PR TITLE
Android Support Library

### PR DESCRIPTION
**Pull request by rawkode**
The Android Support Library shouldn't be included, this will make it easier to integrate with Android projects without messing with the git clone / overriding the jar file.

### CODE REVIEW

**Comment by hwrdprkns** [comment]
Why shouldn't the support library be included? I feel like the project won't build without it?

**Comment by rawkode** [comment]
It wouldn't build without it, but it's up to each individual which version of the support library suits their needs and it'll stop the crazy support library mismatch errors, which in turn disable our ability to update from origin.

**Comment by TomIsYourName** [comment]
It always contain some errors about the support no matter is added or not

**Comment by arslan-anwar** [comment]
I am getting errors to run the code. You should mention step by step prodedure to for developers to use it from begin. Not from code.

**Comment by aisipos** [comment]
+1

When using multiple open source libraries in your app, when they include versions of the support library they tend to conflict, and I have to either fork the library or make manual overrides (that coworkers have to duplicate)  to ensure that all support lib jars are the same.

Although, if you use maven to build, does that solve this problem? I'm not using it currently.

**Pull request closed without merging**
