### PR TITLE
Remove ActionBarSherlock and Maps dependency from library

### PR DESCRIPTION
**Pull request by alfthomas**
As discussed in #205 here is a pull request which removes the ActionBarSherlock and Maps dependency from the SlidingMenu library.

ABS was no longer referenced from the library so I just removed it. Users that merely accidently depended on ABS because they used SlidingMenu will have to explicitly depend on ABS if they intend to use it.

There is only one reference to Maps, in SlidingMapActivity, so I moved it to a separate jar project. Users that need the SlidingMapActivity would need to depend on the slidingmenu-maps-support artifact as well as the library itself to get SlidingMapActivity on their classpath.

Speaking of classpath I have not changed any .classpath files because I do not use or know Eclipse that well.

I had a go at setting up a pom.xml for the example app as well but it turns out that it does not build with the newest SlidingMenu library because BaseActivity expects SlidingFragmentActivity to inherit SherlockFragmentActivity.

### CODE REVIEW

**Comment by jfeinstein10** [comment]
Thanks for this! Sorry it took me so long to get around to it.

**Comment by lejonl** [comment]
Hi I'm new to github, how do I go about if I want to user this version without actionbar sherlock dependency?

**Comment by alfthomas** [comment]
@lejonl This pull request is already merged into master so you just need to clone/fork the master branch, and build/install SlidingMenu to your Maven repository. I'd also love to see @jfeinstein10 tag and release stable versions into Maven central which will make adding SlidingMenu to your project just a few lines of XML if you use Maven. I think there are one or two pull requests open for that.

**Comment by jfeinstein10** [comment]
Thank you for reiterating this again. Every time somebody's said this with regards to SlidingMenu I've asked for help and nobody that's said this has been willing to put their money where their mouth is. It's getting really frustrating because everybody seems to complain and nobody wants to step up and help. If you'd be willing to, that'd be great.

**Comment by alfthomas** [comment]
I think the main reason is that to sync this to Maven Central you need to first publish it to the Sonatype OSS repository and that requires a user account with Sonatype and a PGP signature. It wouldn't make sense if anyone else than the project owner had control over this.

The process is outlined at https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

That said, I think there's still a few snags in the pom.xml that would prohibit it from being accepted into the Sonatype  OSS repo, and those things everyone (and apparently no one...) could fix. I could have a look at creating a pull request for that. There is also the issue of the maps dependency not being in Maven Central so that would probably have to be removed, removing support for MapActivity. I guess that wouldn't be too controversial because it is the old Maps SDK but I don't know how many still use it.

**Comment by lejonl** [comment]
Thanks for the speedy reply, I don't use maven as of yet. I will clone the master then. Cheers!

**Pull request merged**
