### PR TITLE
Minimally Mavenize the project

### PR DESCRIPTION
**Pull request by christopherperry**
Provide at least some minimal support for Maven users. I added a few pom.xml files, and listed the dependencies there. However, there is a jar file you depend on in the examples module that needs to be installed as a third party jar by whoever wants to use your project as a Maven style dependency. This pull will at least let them use the library portion in their project.

### CODE REVIEW

**Comment by christopherperry** [comment]
Forgot to add, the .idea folder is for users of IntelliJ, it has no effect on Eclipse projects, but should be included to support IntelliJ. I added the relevant excludes in the .gitignore file that are recommended here: http://devnet.jetbrains.net/docs/DOC-1186

**Comment by jondwillis** [comment]
You should remove the IntelliJ stuff. It has nothing to do with mavenization.

**Comment by christopherperry** [comment]
@jondwillis Is it the intention of the library to only provide Eclipse IDE support? I see .project and .classpath files in several places.

**Comment by tprochazka** [comment]
+1 for mavenize
Any Idea or Eclipse files is not necessary when project will be mavenized.
Idea can import mavenized project very well, Eclipse was problem with .aplib wen I used it. I don't know current status.

**Comment by svenjacobs** [comment]
+1 for Maven support

and the `.idea` folder should not be checked in. In fact it should be added to `.gitignore`. IntelliJ can import/load a proper Maven project without any problems and will create the necessary files under `.idea` itself.

**Comment by Berglund** [comment]
+1 on this.

**Comment by Shusshu** [comment]
+1 for mavenise but I really do not like this commit because the packagename is also changed.

that means it is more annoying for the author of this lib to pull this change.

And it is not necessary to change the whole package name in order to mavenise it !

**Comment by christopherperry** [comment]
The package must be a domain that the author controls. Does the author own slidingmenu.com? See the naming convention rules:

http://maven.apache.org/guides/mini/guide-naming-conventions.html

**Comment by christopherperry** [comment]
According to JetBrains there are only two files in the .idea folder that should be in .gitignore and those were added in the commit:

http://devnet.jetbrains.com/docs/DOC-1186

**Comment by Shusshu** [comment]
Of course but the author of this lib may not know maven so he didn't even knew about this convention.

You want your pull request to be accepted right? thus make as less changes to the code as you can by creating only a pom.xml and later you can try and convince the author to respect the mentioned conventions

note: the artifactid should already follow the naming convention even if the package name differs.

edit: btw by changing the package name you also break the link to the current example app : https://play.google.com/store/apps/details?id=com.slidingmenu.example
Which will need to be migrated (never did that, maybe it is easy, maybe not)

**Comment by christopherperry** [comment]
If the user wants this library to be more popular than it already is, my suggestion is to properly mavenize it, and get it on Maven Central. A competing library already has this in the works.

**Comment by Avinash-Bhat** [comment]
I guess the developer should look into mavenizing the project ASAP (duplicates: #257, #205, #191)

**Comment by jfeinstein10** [comment]
Alright, a couple things in my defense:
1 - I don't know how to use Maven and definitely don't know how to utilize Maven Central, etc.
2 - I'm a full time university student. I have literally no free time to learn it. Actually zero.
3 - Everybody that I've asked to help me with this and with putting it on Maven Central has said no.

If somebody following this thread would like to finally step up and agree to help setup AND maintain this library on Maven Central, then I would be MORE than happy to work with them. What I'm looking for is for Maven support to be even more minimal, sans package name changing and ABS dependencies.

Hope this helps explain the current non-Mavenized situation.

**Comment by svenjacobs** [comment]
You have to understand that a library without Maven support, which hasn't been even developed with Maven is a pain in the ass for a developer to integrate into his project. With Maven you just add your library as a dependency and all other dependencies are resolved automatically. And learning Maven will really benefit you as a Java/Android developer, too ;-)

I've used the solution by alfthomas (https://github.com/alfthomas/SlidingMenu/tree/mavensupport/), who separated the project into three modules so that dependencies to ABS and Maps are optional. This is the way to go! But since this is not official future updates are not guaranteed.

**Comment by jfeinstein10** [comment]
Yes I understand all that, but like I said; I have no free time to learn it. I need somebody to step up and take the reins on it.

**Comment by svenjacobs** [comment]
The first step would be to merge one of the pull requests regarding Maven support into the project. Once the project is Mavenized people can clone it and install the library into their local Maven repositories - which is a much better situation than now.

**Then** we can think of how to get it into Maven central.

**Comment by Avinash-Bhat** [comment]
@jfeinstein10, if you are not interested in pulling from this request, you can look into the possible [duplicates](https://github.com/jfeinstein10/SlidingMenu/pull/260#issuecomment-13753937) mentioned earlier. or you can cherry-pick any one of them.

**Comment by tjerkw** [comment]
@jfeinstein10 just accept the pull request so people can at least build it with maven.

I understand you don't have time to learn it. But it just as simple as "accept pull request"

It would make your library much, much easier to integrate.

**Comment by Shusshu** [comment]
He won't pull it.
jfeinstein10 said : 

> What I'm looking for is for Maven support to be even more minimal, sans package name changing and ABS dependencies.

I also said the changes should be minimal and this issue title is stating "minimal" but isn't.

Close this issue and take https://github.com/jfeinstein10/SlidingMenu/pull/191

**Comment by tjerkw** [comment]
Ah yeah #191 is also fine, even better. It can evolve from there.

**Comment by christopherperry** [comment]
Yeah, I don't care if mine is pulled, or somebody else's. Something for now is better than nothing. Just keep in mind, if you REALLY want the lib to take off it should be in Maven Central, and the package will need to change.

**Comment by jfeinstein10** [comment]
Why will the package need to change?

**Comment by jfeinstein10** [comment]
Accepted #191

**Comment by tjerkw** [comment]
@jfeinstein10 A java package name is based on domain names. Since slidemenu.com is not yours you should use something else. Sonatype might otherwise refuse your package.

https://docs.sonatype.org/display/Repository/Choosing+your+Coordinates

So either buy slidemenu.com or use a domain name you own, or com.github.jfeinstein10.

However I'm already very happy when it only has a pom file.

**Pull request closed without merging**
