### PR TITLE
Updates slide menu close to trigger on back button key up event

### PR DESCRIPTION
**Pull request by ecgreb**
- Mirrors Android OS behavior for back button handler executing on key up
- Changes instances of onKeyDown to onKeyUp throughout library
- Adds override annotation for methods that override super class or implement an interface
- Removes trailing whitespace

### CODE REVIEW

**Comment by jfeinstein10** [comment]
Thanks for this :)

**Comment by ecgreb** [comment]
Thank you for sharing this project. This is a great resource.

We will hopefully have more to contribute soon.

**Comment by jfeinstein10** [comment]
No problem. It's my gift to the community
Mind if I ask what you're looking into using SlidingMenu for?

**Comment by ecgreb** [comment]
We are experimenting using this style of menu in the upcoming app for howaboutwe.com

**Comment by jfeinstein10** [comment]
Ah super cool! I'll definitely be following your guys' progress. Also, let me know if you guys decide to use SlidingMenu because I'd like a bunch of awesome apps to feature :)

**Comment by ecgreb** [comment]
Absolutely. Do you know of any other apps on Google Play that are currently using this project?

**Comment by jfeinstein10** [comment]
A good example would be PS3 Trophies. Their implementation works well. I worked on an app this summer that I can send you screenshots of as it currently isn't out on the market. I haven't found a good way of contacting GitHub followers to see if anybody else has apps on the market using it. Do you know of any way to do this?

I also recently saw that Time Inc forked my repository for use in their People Magazine app, so that's super exciting!

**Comment by ecgreb** [comment]
I'm not sure if there is a way proactively contact your followers - I am still not that familiar with GitHub's new notification system.

It would be great to check out the screenshots from your app. You can send them to chuck at howaboutwe dot com. Thanks!

**Pull request merged**
