### PR TITLE
Sending a pull request

### PR DESCRIPTION
**Pull request by oliver-snowden-phe**
Roboguice is good...and so is maven :D.  Please review.

@snodnipper

### CODE REVIEW

**Comment by Berglund** [comment]
Oh, maven! This is very interesting. Should be looked into.

**Comment by Konsumierer** [comment]
+1

**Comment by jfeinstein10** [comment]
Does this pull request still apply?

**Comment by oliver-snowden-phe** [comment]
Sorry - the earliest I can look at this in any depth will be in a couple of weeks time.

The main thing of any value was RoboSlidingFragmentActivity[1](https://github.com/oliver-snowden-hpa/SlidingMenu/blob/master/library/src/com/slidingmenu/lib/app/RoboSlidingFragmentActivity.java) as that enables things to be injected easily.  I haven't looked at the great progress you have made in recent times _but_ look forward to seeing the good work soon!

So, other than that, any maven goodness would be appreciated.  Jake's actionbarsherlock project is a good example of maven usage.

Cheers.

**Pull request closed without merging**
