### PR TITLE
Added getter and setter for the touchmode margin threshold

### PR DESCRIPTION
**Pull request by arnestockmans**
If you use TOUCHMODE_MARGIN and want a smaller or larger margin area, you can use the method setTouchmodeMarginThreshold(int marginInPixels) in the class SlidingMenu.

### CODE REVIEW

**Comment by lucasreiners** [comment]
+1

**Comment by alfthomas** [comment]
+1

It would be nice to be able to tweak this.

**Comment by alexbirkett** [comment]
+1

**Comment by menny** [comment]
I'd like to see this get merged too!

**Comment by jfeinstein10** [comment]
Merged!

**Pull request merged**
