### PR TITLE
Move to new Package for Maven Central Prep

### PR DESCRIPTION
**Pull request by donnfelker**
This pull request includes a bunch of changes that move the package from com.slidingmenu.\* to com.jeremyfeinstein.slidingmenu.\* 

Changes Include: 
- Package Rename
- Import renames
- Folder Structure now matches new package name com/jeremyfeinstein/slidingmenu/
- Migration to src/main/java folder structure for Maven Standard Directory Layout
- Updates to gitignore to ignore DS_Store and target/ directory

While I know this change is a breaking change to the library, it is a change that needs to be done eventually as the package name is currently com.slidingmenu which is parked at a domain warehouse which I've contacted already and have not heard back from yet (minimum bid at the time of writing this was 1K for the domain - which is a bit absurd to spend, IMO, for an open source project). 

Once this type of change happens I will help publish it to Maven Central with Jeremy

### CODE REVIEW

**Comment by donnfelker** [comment]
Update: The domain folks got back to me. They want $9,800 for the domain. I'm afraid that won't be happening. :smile:

**Comment by jfeinstein10** [comment]
Hahahah for slidingmenu.com?

**Comment by donnfelker** [comment]
@jfeinstein10 Yes. For slidingmenu.com craziness.

**Comment by jfeinstein10** [comment]
Why is it main.java.com...? Apparently it's not working for some people.

**Comment by donnfelker** [comment]
This is the [standard maven directory layout](http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). Popular projects such as [dagger](https://github.com/square/dagger/tree/master/core/src), [otto](https://github.com/square/otto/tree/master/library/src), [roboguice](https://github.com/roboguice/roboguice/tree/master/roboguice/src) and [Android Bootstrap](https://github.com/donnfelker/android-bootstrap/tree/master/app/src) all use this file structure. 

However, we can revert the change and put the files back into the /src directory to ease the transition/etc. I'll update the files and send a new pull request in a few minutes.

**Comment by jhansche** [comment]
What's the status of this?  I'm currently using a temporary version released to my internal Nexus repository, but would prefer to use an official release version from Maven central.

**Pull request merged**
