### PR TITLE
Created demo of usage with ActionBarSherlock, based off the original example.

### PR DESCRIPTION
**Pull request by iPaulPro**
Depends on ActionBarSherlock 4.x.

### CODE REVIEW

**Comment by ErnestG** [comment]
Why does your example work with 2.3 and up, but the example made by @jfeinstein10 doesn't?

**Comment by ErnestG** [comment]
If you add ABS, does that make 2.3 and up automagically work?

**Comment by iPaulPro** [comment]
@ErnestG The current example relies on APIs that are only available since level 11.

> If you add ABS, does that make 2.3 and up automagically work?

Basically, yes. :-)

**Comment by ErnestG** [comment]
Hmm... alright, one last question. You have the application depend on SlidingMenu and ABS. While @jfeinstein10 has the application depend on SlidingMenu and he instructs you to have SlidingMenu depend on ABS if you want to use it. Why the difference?

**Comment by iPaulPro** [comment]
@ErnestG It's more modular to link ABS to your project, instead of the library for a few reasons. For example: It's easier to keep up with updates (pulls), and you may not always want ABS on every project that you need SlidingMenu for. 

I generally avoid editing the source of a library unless I'm planning on making a pull request.

**Comment by jfeinstein10** [comment]
Correct me if I'm wrong, but the only problem with this approach is that I don't think you can have a sliding ActionBar

**Comment by iPaulPro** [comment]
No, it works perfectly in my demo.

Sliding ActionBarSherlock
Sliding ActionBarSherlock

Not Sliding ActionBarSherlock
Sliding ActionBarSherlock

**Comment by peterfriese** [comment]
Did anyone figure out how to get rid of the little "<" indicator on the home button? I'd like to display just an icon (as known from the Facebook/Path apps)...

**Comment by jfeinstein10** [comment]
getSupportActionBar().setDisplayHomeAsUpEnabled(false);

**Comment by peterfriese** [comment]
When I do this, it will completely disable the home button so I can't use it anymore to active the sliding menu...

**Comment by McPo** [comment]
I have no idea howto post code on github so the below is incorrectly formatted. Heres a link
https://gist.github.com/3655981

You may wish to create your own empty drawable. Because at the moment removing the arrow also removes the padding to the left of the icon

<code>
<resources>
    <style name="Theme.AppTheme" parent="android:Theme.Holo">
        <item name="android:homeAsUpIndicator">@android:color/transparent</item>
    </style>
</resources>
</code>

And apply it to the application, (Be aware of values-v14 etc)

<application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Theme.AppTheme" >

If your using sherlock youll need to double up the xml values as discussed on their website.
Its been tested and works. Let us know if you need any more help.

**Comment by jfeinstein10** [comment]
Closing this because out of date

**Pull request closed without merging**
