### PR TITLE
Example of Issue #121

### PR DESCRIPTION
**Pull request by hwrdprkns**
This is an example of Issue #121. 

I've added a "bugs" section to the Home activity in which you can see the bug referenced in this pull request.

### CODE REVIEW

**Comment by jfeinstein10** [comment]
I totally understand you on this one, but don't really know how to proceed. How would you propose fixing this issue? Is there a way that I can check if other views want to receive Action.MOVE?

**Comment by hwrdprkns** [comment]
Closed because I created another pull request that isn't based off master (so it won't interfere with current development).

I think the way to solve this is to get all the children in the CustomViewAbove and query if any of them respond true to the touch event.

**Comment by jfeinstein10** [comment]
Yeah, that was my only thought. How would you check that for each child?

**Comment by hwrdprkns** [comment]
I'm not sure this is the best solution... but this is my initial pseudocode in the CustomViewAbove.thisSlideAllowed():

```
for(int i=0; i < this.getChildCount(); i++){
            if (this.getChildAt(i) instanceof HorizontalScrollView) {
                Rect r = new Rect();
                this.getChildAt(i).getHitRect(r);
                if (r.contains((int)motionEvent.getX(), (int)motionEvent.getY())) return false;
            }
        }
```

**Comment by hwrdprkns** [comment]
@jfeinstein10 : Actually, I thought of a more open and flexible solutions. See #128

**Pull request closed without merging**
